version: '3'

services:

  # Caddy in here
  caddy:
    image: 'adiatma85/caddy-gg:latest'
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy_data:/data
      - ./caddy_config:/config
  
  # Redis
  redis:
    image: redis:6
    ports:
      - "6379:6379"
    restart: on-failure
    deploy:
      mode: replicated
      replicas: 1
    entrypoint:
      - "redis-server"
    volumes:
      - "./storage/redis/conf:/usr/lib/redis/conf"
      - "./storage/redis/modules:/usr/lib/redis/modules"
      - "./storage/redis/data:/data"

  # Main application in here
  gg-project:
    image: adiatma85/gg-project:latest
    depends_on:
      - caddy
      - redis
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
    restart: on-failure

volumes:
  caddy_data:
    external: true
  caddy_config: